spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cofflib
    username: munir
    password: cofflib
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: create
